### ISSUE TITLE
Which current running kernel

### ISSUE THREAD

**Issue by IRTermite** [IRTermite/kernelBroom#3]
Determine best way to output the current running kernel.
sudo uname -r doesn't show as much detail as the files in /boot

uname -r
3.13.0-44-generic
/boot
3.13.0-44.73

What's a better way?

**Comment by IRTermite** [comment]
Wait, I used dpkg -l linux-image-* | grep ^ii | awk '{print $3}' | sort | uniq | while read readKernels
to generate the list.  So, I am looking at this backwards.

**Comment by bjoernt** [comment]
generic is just a flavor name from ubuntu. The version is still the same and most likely it is the generic flavor, which is installed. So I wouldn't worry about that too much

**Comment by IRTermite** [comment]
True, but then we get things like Installed kernel images in /boot
3.13.0.44.51
3.13.0-44.73
Since I used 
dpkg -l linux-image-* | grep ^ii | awk '{print $3}'

Maybe I should awk on $2 of the output and sort/remove by those lines instead?

**Comment by IRTermite** [comment]
I think I figured it out, but https://github.com/IRTermite/kernelBroom/blob/master/kernelBroom.sh#L52 is still not quite right.  It won't remove the line from the tmp file.

**Comment by IRTermite** [comment]
@BjoernT , I hate you!

(05:39:27 PM) bjoern: just do a "grep -v $currentKernel $kernelBroomTmp > ${kernelBroomTmp}.tmp && mv ${kernelBroomTmp}.tmp ${kernelBroomTmp}"
